### ISSUE TITLE
The Skills of Living book available?

### ISSUE THREAD

**Issue by phoenixic** [jackiewoodall/twb#2]
I'm looking for the "The Skills of Living" book as it was referenced in Taming the Drunken Monkey book but the web address given in the book is incorrect and I can not find the book at all.

**Comment by jackiewoodall** [comment]
Fortunately, these have been preserved in web.archive.org.

Skills of Living: https://web.archive.org/web/20151125172732/http://uwf.edu/wmikulas/Webpage/skills/preface.htm

/wmikulas/books: https://web.archive.org/web/20160326091544/http://uwf.edu/wmikulas/Webpage/books.htm
